# Generated by Django 5.0.7 on 2024-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapcomments',
            name='likes',
            field=models.ManyToManyField(related_name='comment_likes', to='user.user'),
        ),
    ]
