version: '3' #docker-compose 버전을 나타냄
services: 
  nginx: 
    image: nginx:latest
    ports: 
      - "80:80"
     
    volumes: 
      - .:/code #현재 위치와 /code(django 어플리케이션이 있는 위치) 
      - ./test_page/nginx:/etc/nginx/conf.d #niginx 설정파일이 있는 위치
    depends_on: #컨테이너 의존관계를 의미한다.
      - web #아래 적혀있음

  web:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes: 
      - .:/code
    ports:
      - "8000:8000"